/** Node crypto implementation. SHA-1 remains the default for existing ciphertext. */
import * as crypto from 'crypto';
import { decode, hasPEMEnvelope } from '../shared/helpers';
import {
  resolveOaepHash, hybridOptions, serializeHybrid, parseHybrid, requireAes256Key, strictBase64,
} from '../shared/hybrid';
import type {
  parametersOfDecrypt, parametersOfDecryptPublic, parametersOfEncrypt, parametersOfEncryptLarge,
  parametersOfEncryptPrivate, parametersOfSign, parametersOfVerify, returnCreateKeys, OaepHash,
} from '../shared/types';

function oaepOptions(hash?: OaepHash) {
  return { padding: crypto.constants.RSA_PKCS1_OAEP_PADDING, oaepHash: resolveOaepHash(hash) };
}

function publicKeyFrom(encoded: string): crypto.KeyObject {
  try {
    const key = crypto.createPublicKey(decode(encoded));
    if (key.asymmetricKeyType !== 'rsa') throw new Error('Expected RSA');
    return key;
  } catch (_) {
    throw new Error('Invalid public key format. Expected an RSA public key in PEM format.');
  }
}

function privateKeyFrom(encoded: string): crypto.KeyObject {
  try {
    const key = crypto.createPrivateKey(decode(encoded));
    if (key.asymmetricKeyType !== 'rsa') throw new Error('Expected RSA');
    return key;
  } catch (_) {
    throw new Error('Invalid private key format. Expected an RSA private key in PEM format.');
  }
}

export function encryptStringWithRsaPublicKey(args: parametersOfEncrypt): string {
  const key = publicKeyFrom(args.publicKey as string);
  return crypto.publicEncrypt({ key, ...oaepOptions(args.oaepHash) }, Buffer.from(args.text)).toString('base64');
}

export function decryptStringWithRsaPrivateKey(args: parametersOfDecrypt): string {
  const key = privateKeyFrom(args.privateKey as string);
  return crypto.privateDecrypt({ key, ...oaepOptions(args.oaepHash) }, Buffer.from(args.text, 'base64')).toString('utf8');
}

/** Legacy by default; opt into v1 for an authenticated algorithm header. */
export function encryptLarge(args: parametersOfEncryptLarge): string {
  const key = publicKeyFrom(args.publicKey as string);
  const { hash, header } = hybridOptions(args);
  const aesKey = crypto.randomBytes(32);
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv('aes-256-gcm', aesKey, iv, { authTagLength: 16 });
  if (header) cipher.setAAD(Buffer.from(header, 'utf8'));
  const ciphertext = Buffer.concat([cipher.update(args.text, 'utf8'), cipher.final()]);
  const encryptedKey = crypto.publicEncrypt({ key, ...oaepOptions(hash) }, aesKey);
  return serializeHybrid(header, [encryptedKey, iv, cipher.getAuthTag(), ciphertext]);
}

export function decryptLarge(args: parametersOfDecrypt): string {
  const payload = parseHybrid(args.text, args.oaepHash);
  const key = privateKeyFrom(args.privateKey as string);
  try {
    const aesKey = crypto.privateDecrypt({ key, ...oaepOptions(payload.hash) }, payload.encryptedKey);
    requireAes256Key(aesKey);
    const decipher = crypto.createDecipheriv('aes-256-gcm', aesKey, payload.iv, { authTagLength: 16 });
    if (payload.header) decipher.setAAD(Buffer.from(payload.header, 'utf8'));
    decipher.setAuthTag(payload.tag);
    return Buffer.concat([decipher.update(payload.ciphertext), decipher.final()]).toString('utf8');
  } catch (_) {
    throw new Error('Decryption failed. Ensure you are using the correct private key and an unmodified payload produced by encryptLarge.');
  }
}

/** Legacy private-key operation; use sign/verify for authentication. */
export function encryptPrivate(args: parametersOfEncryptPrivate): string {
  return crypto.privateEncrypt(privateKeyFrom(args.privateKey as string), Buffer.from(args.text)).toString('base64');
}

export function decryptPublic(args: parametersOfDecryptPublic): string {
  return crypto.publicDecrypt(publicKeyFrom(args.publicKey as string), Buffer.from(args.text, 'base64')).toString('utf8');
}

export function sign(args: parametersOfSign): string {
  return crypto.sign('sha256', Buffer.from(args.text, 'utf8'), {
    key: privateKeyFrom(args.privateKey as string),
    padding: crypto.constants.RSA_PKCS1_PSS_PADDING,
    saltLength: 32,
  }).toString('base64');
}

export function verify(args: parametersOfVerify): boolean {
  const key = publicKeyFrom(args.publicKey as string);
  let signature: Uint8Array;
  try {
    signature = strictBase64(args.signature);
  } catch (_) {
    return false;
  }
  return crypto.verify('sha256', Buffer.from(args.text, 'utf8'), {
    key, padding: crypto.constants.RSA_PKCS1_PSS_PADDING, saltLength: 32,
  }, signature);
}

/** Parses SPKI RSA public key material; formatting alone is insufficient. */
export async function isValidRSAPublicKey(key: unknown): Promise<boolean> {
  if (!hasPEMEnvelope(key, 'public')) return false;
  try {
    return crypto.createPublicKey(key as string).asymmetricKeyType === 'rsa';
  } catch (_) {
    return false;
  }
}

/** Parses PKCS#8 RSA private key material, matching keys generated by this package. */
export async function isValidRSAPrivateKey(key: unknown): Promise<boolean> {
  if (!hasPEMEnvelope(key, 'private')) return false;
  try {
    return crypto.createPrivateKey(key as string).asymmetricKeyType === 'rsa';
  } catch (_) {
    return false;
  }
}

export function createPrivateAndPublicKeys(modulusLength: number = 2048): Promise<returnCreateKeys> {
  return new Promise((resolve, reject) => {
    crypto.generateKeyPair('rsa', {
      modulusLength,
      publicKeyEncoding: { type: 'spki', format: 'pem' },
      privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
    }, (error, publicKey, privateKey) => {
      if (error) reject(error);
      else resolve({ publicKey, privateKey });
    });
  });
}
